import { Alert, Machine, TelemetryPreset } from "@/types";

export const FAILURE_PRESETS: TelemetryPreset[] = [
  {
    id: "nominal",
    name: "Nominal Healthy Operation",
    short_code: "NOMINAL",
    description: "Standard balanced cutting cycle with normal thermal and torque envelopes.",
    physical_cause: "Balanced spindle speeds, nominal cutting torque, and minimal insert wear.",
    expected_outcome: "HEALTHY (Risk < 1.0%)",
    telemetry: {
      type: "M",
      air_temperature_k: 298.1,
      process_temperature_k: 308.6,
      rotational_speed_rpm: 1550.0,
      torque_nm: 40.0,
      tool_wear_min: 30.0,
    },
  },
  {
    id: "hdf",
    name: "Heat Dissipation Failure (HDF)",
    short_code: "HDF",
    description: "Cooling system collapse: Temperature delta ΔT < 8.6 K with sub-1380 RPM.",
    physical_cause: "Coolant starvation or radiator blockage impeding thermal transfer.",
    expected_outcome: "FAILURE IMMINENT (Risk ~95%)",
    telemetry: {
      type: "L",
      air_temperature_k: 302.8,
      process_temperature_k: 311.2,
      rotational_speed_rpm: 1360.0,
      torque_nm: 52.0,
      tool_wear_min: 105.0,
    },
  },
  {
    id: "pwf",
    name: "Power Overload Failure (PWF)",
    short_code: "PWF",
    description: "Spindle drive overload: Electrical/Mechanical power exceeds 9,000 W.",
    physical_cause: "Excessive cutting depth or workpiece binding causing electrical draw spike.",
    expected_outcome: "FAILURE IMMINENT (Risk ~98%)",
    telemetry: {
      type: "L",
      air_temperature_k: 300.5,
      process_temperature_k: 310.8,
      rotational_speed_rpm: 2840.0,
      torque_nm: 65.0,
      tool_wear_min: 35.0,
    },
  },
  {
    id: "osf",
    name: "Overstrain Mechanical Failure (OSF)",
    short_code: "OSF",
    description: "High mechanical torque (>60 Nm) combined with exhausted cutting tool wear (>200 min).",
    physical_cause: "Severe cutting force exceeding material yield strength of the worn tool insert.",
    expected_outcome: "CRITICAL FAILURE (Risk ~97%)",
    telemetry: {
      type: "L",
      air_temperature_k: 302.5,
      process_temperature_k: 311.8,
      rotational_speed_rpm: 1380.0,
      torque_nm: 62.5,
      tool_wear_min: 215.0,
    },
  },
  {
    id: "twf",
    name: "Tool Wear Insert Failure (TWF)",
    short_code: "TWF",
    description: "Cumulative tool wear exceeds permissible 200–240 min cutting lifespan.",
    physical_cause: "Excessive flank and crater wear causing sudden chatter and fracture.",
    expected_outcome: "FAILURE IMMINENT (Risk ~92%)",
    telemetry: {
      type: "M",
      air_temperature_k: 299.0,
      process_temperature_k: 309.2,
      rotational_speed_rpm: 1420.0,
      torque_nm: 48.0,
      tool_wear_min: 240.0,
    },
  },
];

export const MOCK_MACHINES: Machine[] = [
  {
    id: "CNC-001",
    name: "5-Axis High Precision Mill",
    type: "H",
    location: "Bay A - Precision Cell",
    status: "HEALTHY",
    failure_probability: 0.012,
    last_prediction_time: "2 mins ago",
    telemetry: {
      type: "H",
      air_temperature_k: 297.8,
      process_temperature_k: 308.2,
      rotational_speed_rpm: 1540,
      torque_nm: 38.5,
      tool_wear_min: 42,
      udi: 1001,
      product_id: "H31401",
    },
    derived: {
      power_w: 6208,
      temp_diff_k: 10.4,
      overstrain_index: 1617,
      tool_wear_rate: 0.027,
    },
  },
  {
    id: "CNC-002",
    name: "CNC Heavy Lathe Alpha",
    type: "L",
    location: "Bay B - Heavy Turning",
    status: "CRITICAL",
    failure_probability: 0.941,
    last_prediction_time: "Just now",
    warning_message: "Overstrain Failure (OSF) Risk - High torque (62.5 Nm) & tool wear (215 min)",
    telemetry: {
      type: "L",
      air_temperature_k: 302.5,
      process_temperature_k: 311.8,
      rotational_speed_rpm: 1380,
      torque_nm: 62.5,
      tool_wear_min: 215,
      udi: 1002,
      product_id: "L47102",
    },
    derived: {
      power_w: 9032,
      temp_diff_k: 9.3,
      overstrain_index: 13437,
      tool_wear_rate: 0.155,
    },
  },
  {
    id: "CNC-003",
    name: "Horizontal Machining Center",
    type: "M",
    location: "Bay A - Production Line 1",
    status: "WARNING",
    failure_probability: 0.684,
    last_prediction_time: "5 mins ago",
    warning_message: "Elevated thermal gradient ΔT (8.5 K) approaching HDF boundary",
    telemetry: {
      type: "M",
      air_temperature_k: 301.9,
      process_temperature_k: 310.4,
      rotational_speed_rpm: 1375,
      torque_nm: 51.0,
      tool_wear_min: 110,
      udi: 1003,
      product_id: "M21803",
    },
    derived: {
      power_w: 7343,
      temp_diff_k: 8.5,
      overstrain_index: 5610,
      tool_wear_rate: 0.080,
    },
  },
  {
    id: "CNC-004",
    name: "Vertical Spindle Drill #4",
    type: "M",
    location: "Bay C - Drilling Bay",
    status: "HEALTHY",
    failure_probability: 0.008,
    last_prediction_time: "12 mins ago",
    telemetry: {
      type: "M",
      air_temperature_k: 298.5,
      process_temperature_k: 308.9,
      rotational_speed_rpm: 1620,
      torque_nm: 36.0,
      tool_wear_min: 18,
      udi: 1004,
      product_id: "M21904",
    },
    derived: {
      power_w: 6110,
      temp_diff_k: 10.4,
      overstrain_index: 648,
      tool_wear_rate: 0.011,
    },
  },
  {
    id: "CNC-005",
    name: "CNC High-Torque Milling Center",
    type: "L",
    location: "Bay B - Roughing Area",
    status: "WARNING",
    failure_probability: 0.582,
    last_prediction_time: "18 mins ago",
    warning_message: "Spindle power draw 8,850 W nearing PWF trip limit (9,000 W)",
    telemetry: {
      type: "L",
      air_temperature_k: 300.2,
      process_temperature_k: 310.1,
      rotational_speed_rpm: 2750,
      torque_nm: 61.5,
      tool_wear_min: 45,
      udi: 1005,
      product_id: "L47205",
    },
    derived: {
      power_w: 17710,
      temp_diff_k: 9.9,
      overstrain_index: 2767,
      tool_wear_rate: 0.016,
    },
  },
  {
    id: "CNC-006",
    name: "Precision Surface Grinder 02",
    type: "H",
    location: "Bay A - Finishing",
    status: "HEALTHY",
    failure_probability: 0.003,
    last_prediction_time: "25 mins ago",
    telemetry: {
      type: "H",
      air_temperature_k: 297.2,
      process_temperature_k: 307.8,
      rotational_speed_rpm: 1510,
      torque_nm: 34.0,
      tool_wear_min: 15,
      udi: 1006,
      product_id: "H31506",
    },
    derived: {
      power_w: 5376,
      temp_diff_k: 10.6,
      overstrain_index: 510,
      tool_wear_rate: 0.009,
    },
  },
  {
    id: "CNC-007",
    name: "5-Axis Gantry Mill Beta",
    type: "L",
    location: "Bay D - Heavy Aerospace",
    status: "HEALTHY",
    failure_probability: 0.045,
    last_prediction_time: "30 mins ago",
    telemetry: {
      type: "L",
      air_temperature_k: 298.9,
      process_temperature_k: 309.5,
      rotational_speed_rpm: 1490,
      torque_nm: 44.0,
      tool_wear_min: 88,
      udi: 1007,
      product_id: "L47307",
    },
    derived: {
      power_w: 6865,
      temp_diff_k: 10.6,
      overstrain_index: 3872,
      tool_wear_rate: 0.059,
    },
  },
  {
    id: "CNC-008",
    name: "Automated Tooling Cell 8",
    type: "M",
    location: "Bay C - Automation Row",
    status: "HEALTHY",
    failure_probability: 0.019,
    last_prediction_time: "35 mins ago",
    telemetry: {
      type: "M",
      air_temperature_k: 299.1,
      process_temperature_k: 309.4,
      rotational_speed_rpm: 1580,
      torque_nm: 39.0,
      tool_wear_min: 65,
      udi: 1008,
      product_id: "M22008",
    },
    derived: {
      power_w: 6452,
      temp_diff_k: 10.3,
      overstrain_index: 2535,
      tool_wear_rate: 0.041,
    },
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: "ALT-9041",
    machine_id: "CNC-002",
    machine_name: "CNC Heavy Lathe Alpha",
    timestamp: "10:42:15 UTC",
    issue: "Critical Overstrain Index (13,437 Nm·min) exceeding safe threshold (11,000 Nm·min)",
    failure_type: "OSF",
    severity: "CRITICAL",
    recommended_action: "Immediately stop spindle cycle. Inspect cutting insert for micro-fractures and replace tool before resuming pass.",
    acknowledged: false,
    telemetry_snapshot: {
      type: "L",
      air_temperature_k: 302.5,
      process_temperature_k: 311.8,
      rotational_speed_rpm: 1380,
      torque_nm: 62.5,
      tool_wear_min: 215,
    },
  },
  {
    id: "ALT-9038",
    machine_id: "CNC-003",
    machine_name: "Horizontal Machining Center",
    timestamp: "10:28:40 UTC",
    issue: "Cooling fluid flow rate degradation. Temperature delta ΔT dropped to 8.5 K.",
    failure_type: "HDF",
    severity: "WARNING",
    recommended_action: "Verify auxiliary coolant pressure and check chip conveyor filter for metal swarf blockage.",
    acknowledged: false,
    telemetry_snapshot: {
      type: "M",
      air_temperature_k: 301.9,
      process_temperature_k: 310.4,
      rotational_speed_rpm: 1375,
      torque_nm: 51.0,
      tool_wear_min: 110,
    },
  },
  {
    id: "ALT-9035",
    machine_id: "CNC-005",
    machine_name: "CNC High-Torque Milling Center",
    timestamp: "09:55:12 UTC",
    issue: "Spindle peak power surge reached 17.7 kW under heavy workpiece cutting pass.",
    failure_type: "PWF",
    severity: "WARNING",
    recommended_action: "Reduce feed rate by 15% on deep pocket roughing cycle to avoid servo inverter trip.",
    acknowledged: true,
  },
  {
    id: "ALT-9022",
    machine_id: "CNC-001",
    machine_name: "5-Axis High Precision Mill",
    timestamp: "08:15:00 UTC",
    issue: "Scheduled 50-hour lubrication cycle routine completed successfully.",
    failure_type: "GENERAL",
    severity: "INFO",
    recommended_action: "Log inspection status in maintenance logbook. No operator intervention required.",
    acknowledged: true,
  },
];

export const MOCK_TELEMETRY_SERIES = [
  { time: "08:00", air_temp: 297.5, proc_temp: 307.8, temp_diff: 10.3, speed: 1540, torque: 38.0, power: 6127, wear: 180, failure_prob: 0.08 },
  { time: "08:30", air_temp: 298.1, proc_temp: 308.5, temp_diff: 10.4, speed: 1530, torque: 39.5, power: 6328, wear: 188, failure_prob: 0.12 },
  { time: "09:00", air_temp: 299.2, proc_temp: 309.4, temp_diff: 10.2, speed: 1510, torque: 42.0, power: 6641, wear: 195, failure_prob: 0.19 },
  { time: "09:30", air_temp: 300.5, proc_temp: 310.2, temp_diff: 9.7, speed: 1470, torque: 46.5, power: 7158, wear: 202, failure_prob: 0.35 },
  { time: "10:00", air_temp: 301.8, proc_temp: 311.0, temp_diff: 9.2, speed: 1420, torque: 54.0, power: 8030, wear: 210, failure_prob: 0.68 },
  { time: "10:30", air_temp: 302.5, proc_temp: 311.8, temp_diff: 9.3, speed: 1380, torque: 62.5, power: 9032, wear: 215, failure_prob: 0.94 },
];

export const GLOBAL_FEATURE_IMPORTANCE = [
  { name: "Overstrain Index", key: "overstrain_index", importance: 0.312, domain: "Mechanical Stress" },
  { name: "Mechanical Power (P=τω)", key: "power_w", importance: 0.228, domain: "Electrical & Inverter" },
  { name: "Tool Wear Duration", key: "tool_wear_min", importance: 0.165, domain: "Tooling Life" },
  { name: "Mechanical Torque", key: "torque_nm", importance: 0.124, domain: "Spindle Force" },
  { name: "Tool Wear Rate", key: "tool_wear_rate", importance: 0.082, domain: "Tribology" },
  { name: "Temperature Delta (ΔT)", key: "temp_difference_k", importance: 0.051, domain: "Thermodynamics" },
  { name: "Rotational Speed", key: "rotational_speed_rpm", importance: 0.024, domain: "Kinematics" },
  { name: "Quality Variant (Type)", key: "type", importance: 0.014, domain: "Metadata" },
];
